dist: trusty
language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: true

install:
  - pip install -U pip setuptools
  - pip install -U pytest
  - pip install -r requirements.txt
  - pip install -U -e .[test]

script:
  - bin/pytest src
